{
  "formatVersion": "1.1",
  "component": {
    "group": "kmmshared",
    "module": "shared",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared-metadata-0.0.1-all.jar",
          "url": "shared-0.0.1-all.jar",
          "size": 4982,
          "sha512": "c673d58b90d63c89b54682dd405640e8b8191ddbc05d524ff9f65bbda049494a217f4466f667aeaca4f0534cf24866d1a0aafe342d7a9e1d753fd36a8c3365f6",
          "sha256": "71b29f50e50d3a466958a451293c6f2f0d011be23d030eaf58c80767df36f4bd",
          "sha1": "67b6606e0b86f6d8906705c72c02d10a31762e8f",
          "md5": "7001b900d7a51e72b2a2e52264877eca"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "shared-0.0.1.jar",
          "url": "shared-0.0.1.jar",
          "size": 5425,
          "sha512": "461214d55a6d57dd336bc987489f9db41264b472bf88173f583c8d129620f990a544ad71ab0b5216fda7e38a39d9616d7650bb83431ec92781badaf1cd69d182",
          "sha256": "9bc4e11bfbf1d61fd4fe38ad2fd46d84833385a477aebfddc498793984fd664f",
          "sha1": "fc0bb452d82435329c6d0016fc633e3696449fd6",
          "md5": "4ed4e4af1fb87e07fd382a8ad383b840"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../shared-android/0.0.1/shared-android-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../shared-android/0.0.1/shared-android-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../shared-android/0.0.1/shared-android-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../shared-android/0.0.1/shared-android-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.0.1/shared-iosarm64-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.0.1/shared-iosarm64-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosx64/0.0.1/shared-iosx64-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosx64/0.0.1/shared-iosx64-0.0.1.module",
        "group": "kmmshared",
        "module": "shared-iosx64",
        "version": "0.0.1"
      }
    }
  ]
}
