{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/0.0.1/shared-0.0.1.module",
    "group": "kmmshared",
    "module": "shared",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared.klib",
          "url": "shared-iosarm64-0.0.1.klib",
          "size": 26002,
          "sha512": "ac9a7bd0df0df2ed13cd8ce889b4e4f84ef01f862084e6a2d038204cb03eb068ad38a8ddc8e1bc4229e994be5012c6c723f1d1f68cfd875d42598531ebd63c52",
          "sha256": "c8cc979e75967b877447df5f0a3817fa85e57e9fde1472f007b47230d08cd321",
          "sha1": "bff3fe222c5ee044228f9c60f7f89e219ff37b13",
          "md5": "1c34475d5b5cb34f774f26caad6ac9be"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosarm64-0.0.1-metadata.jar",
          "url": "shared-iosarm64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "2b848aa86b246571d1e50edd508790e5a81a445b0b503c1180ad661af07a844124f24ba5e9ec5f8dbe3922d69fd889f3fa3cfb7ecffee6b461ed161be9d15c36",
          "sha256": "9c232044357479ea7e9cae97a1cad8eaa811491f9f968894632415b8594e2d49",
          "sha1": "8702985a74897c2011c43aa9cad8162fcd4f7f12",
          "md5": "2a822f2d63744fb655806d0b758d3826"
        }
      ]
    }
  ]
}
