{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shared/0.0.1/shared-0.0.1.module",
    "group": "kmmshared",
    "module": "shared",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared.klib",
          "url": "shared-iosx64-0.0.1.klib",
          "size": 25985,
          "sha512": "0eaf878aa65f137d969a975056d4a5667920690400f06e0200dd0e85fc607a03623467536c3c6cb5d5c7ce006bdfe8434c629f38694c7cde0d1829317e533634",
          "sha256": "15c9c7d11ac58b9f57dd2f002587e93d47a1f52a492fd1e9ecc17d6ba6e0a654",
          "sha1": "96a33ed6721d853eec831f4c99f24a747cc3eb37",
          "md5": "62fd1e700705cfd0f382ef386809d9bf"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosx64-0.0.1-metadata.jar",
          "url": "shared-iosx64-0.0.1-metadata.jar",
          "size": 261,
          "sha512": "2b848aa86b246571d1e50edd508790e5a81a445b0b503c1180ad661af07a844124f24ba5e9ec5f8dbe3922d69fd889f3fa3cfb7ecffee6b461ed161be9d15c36",
          "sha256": "9c232044357479ea7e9cae97a1cad8eaa811491f9f968894632415b8594e2d49",
          "sha1": "8702985a74897c2011c43aa9cad8162fcd4f7f12",
          "md5": "2a822f2d63744fb655806d0b758d3826"
        }
      ]
    }
  ]
}
